import os.path
from ase.io import iread,write
from .work_dir import bsub_dir
import glob
import pickle
from ..path_names import DFT_WORK_DIR, MD_WORK_DIR

def mkdir(dir):
    if not os.path.exists(dir):
        os.mkdir(dir)

'''生成DFT相关目录，记录未收敛的结构(stru.pkl)，返回需要DFT的结构'''
def collect_dft_data(delete_filter_select,pwd):
    total_atom_list = []
    dft_work_path = os.path.join(pwd, DFT_WORK_DIR)
    scf = os.path.join(dft_work_path,'scf')
    #total_sample_filter_path = os.path.join(scf,'total_sample_filter.xyz')

    mkdir(dft_work_path)
    mkdir(scf)
    stru_list = []
    stru_pkl = os.path.join(pwd,'stru.pkl')

    # Encoded-sampling mode writes selected DFT structures to sus2-md/*_sample_filter.xyz.
    work_sample_files = sorted(glob.glob(os.path.join(pwd, MD_WORK_DIR, '*_sample_filter.xyz')))
    if work_sample_files:
        for sample_file in work_sample_files:
            total_atom_list.extend(list(iread(sample_file)))
        # Keep stru.pkl generated by mlp_return_strupkl untouched.
        # It records which original stru/*.vasp systems should seed the next MD round.
        return total_atom_list

    for dir in bsub_dir(pwd):
        os.chdir(dir)
        delete = glob.glob('*filter*')
        sample = [i for i in delete if 'sample' in i]
        delete = [i for i in delete if 'remain' in i]
        if len(sample) != 0:
            stru_list.append(os.path.basename(dir)+'.vasp')
            total_atom_list = total_atom_list + list(iread(sample[0]))
        if delete_filter_select == 'yes':
            for i in delete:
                if os.path.exists(i):
                    os.remove(i)
    with open(stru_pkl, 'wb') as f:
        pickle.dump(stru_list, f)
    #write(total_sample_filter_path,total_atom_list,format='extxyz')
    return total_atom_list


